### PR TITLE
Fixes user facing CLI and services messages and also related tests.

### PR DESCRIPTION
**Pull request by aveshagarwal**

### CODE REVIEW

**Comment by cgwalters** [comment]
Can we say "Renamed" instead of "Fixed"?

Also this is minor but can we not use periods at the end of commit messages?  It doesn't match the existing openshift/origin style.  I write all my commit messages Linux kernel style FWIW.

**Comment by cgwalters** [comment]
e.g. `client: Rename CLI messages for Atomic Enterprise`

**Comment by aveshagarwal** [comment]
Agree, will amend commit messages now.

**Comment by aveshagarwal** [comment]
@cgwalters @giuseppe I have pushed updated PR for review.

**Comment by cgwalters** [comment]
Like the commit messages much better, thanks! :+1:

**Pull request merged**
